services:
  # Servicio de la API en Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Usa Dockerfile.dev para desarrollo
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al host
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules  # Para evitar conflictos de `node_modules` locales
    command: npx nodemon src/app.js  # Usa nodemon para recarga automática

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3308:3306"  # Mapea el puerto 3306 del contenedor al 3308 del host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
