version: '3.8'

services:
  # Servicio de la API en Node.js
  api:
    build: .
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al host
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=academia_ingles
      - JWT_SECRET=supersecretkey
    depends_on:
      - db

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: academia_ingles
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
